/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import static Project.ManageDocuments.db;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Musse
 */
public class AddAssigment extends javax.swing.JInternalFrame {
ConnectionClass db = new ConnectionClass(); //skapar connection till databas

    private Locale l;//VARJE KLASS
    /**
     * Creates new form NewJInternalFrame
     */
    public AddAssigment() {
        initComponents();
        String name = "";
        String info = "";
        
        fillAssignmentCMB();
        initializeLanguage();//VARJE KLASS 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAssigment().setVisible(true);
                
                
            }
        });
    }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Name = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLabel_info = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField_info = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        ShowInfo = new javax.swing.JButton();
        Combo_Assigment = new javax.swing.JComboBox();
        jButton_AddAssigment = new javax.swing.JButton();
        Remove_delete = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Project/Bundle"); // NOI18N
        jButton1.setText(bundle.getString("AddAssigment.jButton1.text")); // NOI18N

        setTitle(bundle.getString("AddAssigment.title")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Name.setText(bundle.getString("AddAssigment.jLabel_Name.text")); // NOI18N

        jLabel_info.setText(bundle.getString("AddAssigment.jLabel_info.text")); // NOI18N

        jTextField_info.setColumns(20);
        jTextField_info.setRows(5);
        jTextField_info.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_infoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextField_info);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_info, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_info, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Name.getAccessibleContext().setAccessibleName(bundle.getString("AddAssigment.jLabel_Name.AccessibleContext.accessibleName")); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ShowInfo.setText(bundle.getString("AddAssigment.ShowInfo.text")); // NOI18N
        ShowInfo.setName("jButton_showInfo"); // NOI18N
        ShowInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowInfoActionPerformed(evt);
            }
        });

        Combo_Assigment.setName("assignmentsCMB"); // NOI18N

        jButton_AddAssigment.setText(bundle.getString("AddAssigment.jButton_AddAssigment.text")); // NOI18N
        jButton_AddAssigment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddAssigmentActionPerformed(evt);
            }
        });

        Remove_delete.setText(bundle.getString("AddAssigment.Remove_delete.text")); // NOI18N
        Remove_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Combo_Assigment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowInfo)
                            .addComponent(jButton_AddAssigment, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Remove_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Combo_Assigment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_AddAssigment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Remove_delete)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        setBounds(0, 0, 668, 398);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * lägger till en assigment till databasen och rensar text fälten efteråt
     */
    private void jButton_AddAssigmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddAssigmentActionPerformed
        try
        { 
            String Query = "insert into assignment(name, info) values('" + jTextField_Name.getText() + "', '" + jTextField_info.getText() + "')";
             db.query(Query);
             
             fillAssignmentCMB();
             
             jTextField_Name.setText("");
             jTextField_info.setText("");
        }
   
       /* query("insert into users(name, email, username, password, status) values ('niklas', 'niklas', 'niklas', 'nilkas', 3);");*/
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Det gick inte att lägga till ett assignment");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddAssigmentActionPerformed
    
    /**
     * Tar bort en vald assigment och tar alla referenser till den
     */
    private void Remove_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_deleteActionPerformed
        
        try
        {
            String assignment = Combo_Assigment.getSelectedItem().toString();
            
            String Query1 = "Delete Report, Assignment from Report join assignment on Report.AssignmentID = assignment.AssignmentID where assignment.name = '" + assignment + "';Delete receipt, assignment, Report from receipt join Report on Report.ReportID = receipt.ReportID join assignment on assignment.AssignmentID = Report.AssignmentID where assignment.name = '" + assignment + "'; Delete traveladvances, assignment from traveladvances join assignment on assignment.assignmentID = traveladvances.assignmentID where assignment.name = '" + assignment + "'; Delete Trip, assignment from Trip join assignment on assignment.AssignmentID = Trip.AssignmentID where assignment.name = '" + assignment + "'; Delete from assignment where name = '" + assignment + "'";
                      
          
            String[] Queries = new String[]
            {"Delete Report, Assignment from Report join assignment on Report.AssignmentID = assignment.AssignmentID where assignment.name = '" + assignment + "'",
             "Delete receipt, assignment, report from receipt join Report on Report.ReportID = receipt.ReportID join assignment on assignment.AssignmentID = Report.AssignmentID where assignment.name = '" + assignment + "'",
             "Delete traveladvances, assignment from traveladvances join assignment on assignment.assignmentID = traveladvances.assignmentID where assignment.name = '" + assignment + "'",
             "Delete Trip, assignment from Trip join assignment on assignment.AssignmentID = Trip.AssignmentID where assignment.name = '" + assignment + "'",
             "Delete from assignment where name = '" + assignment + "'"
            };
            
            db.executeMultiple(Queries);
            
            fillAssignmentCMB();
            jTextField_Name.setText("");
            jTextField_info.setText("");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_Remove_deleteActionPerformed
   
    /**
     * visar info om en specifik assigment som hämtas ifrån databasen
     */
    private void ShowInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowInfoActionPerformed
        // TODO add your handling code here:
        
        
        if(Combo_Assigment.getSelectedItem() != null)          
        {
            try
            {
                String Query = "Select * from assignment where name = '" + Combo_Assigment.getSelectedItem().toString() + "'";
                ResultSet rs = db.getColumn(Query);
        
                while(rs.next())
                {
                    jTextField_Name.setText(rs.getString("name"));
                    jTextField_info.setText(rs.getString("info"));
                }
            
            }   
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please choose an assignment");
        }
    }//GEN-LAST:event_ShowInfoActionPerformed

    private void jTextField_infoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_infoKeyPressed
if(evt.getKeyCode() ==KeyEvent.VK_ENTER){       
     try
        { 
            String Query = "insert into assignment(name, info) values('" + jTextField_Name.getText() + "', '" + jTextField_info.getText() + "')";
             db.query(Query);
             
             fillAssignmentCMB();
             
             jTextField_Name.setText("");
             jTextField_info.setText("");
        }
   
       /* query("insert into users(name, email, username, password, status) values ('niklas', 'niklas', 'niklas', 'nilkas', 3);");*/
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Det gick inte att lägga till ett assignment");
        }
       


}
    }//GEN-LAST:event_jTextField_infoKeyPressed
           private void initializeLanguage(){//HELA METODEN I VARJE KLASS MODIFIERAT
               
            l = LogIn.getString();
         
        ResourceBundle r = ResourceBundle.getBundle("Project/Bundle", l);{
               
          jButton_AddAssigment.setText(r.getString("AddAssigment.jButton_AddAssigment.text"));
           ShowInfo.setText(r.getString("AddAssigment.ShowInfo.text"));
            jLabel_info.setText(r.getString("AddAssigment.jLabel_info.text"));
             jLabel_Name.setText(r.getString("AddAssigment.jLabel_Name.AccessibleContext.accessibleName"));
              jLabel_Name.setText(r.getString("AddAssigment.jLabel_Name.text")); 
               jButton1.setText(r.getString("AddAssigment.jButton1.text"));
                 Remove_delete.setText(r.getString("AddAssigment.Remove_delete.text"));
        
       
           
           }
           
       }

    /**
     * fyller comboboxen med alla assigment
     */
    private void  fillAssignmentCMB()
    {
       try
        {
            Combo_Assigment.removeAllItems();
        String Query = "Select name from Assignment";  
        
        ResultSet rs = db.getColumn(Query);
        
        while(rs.next())
        {
            Combo_Assigment.addItem(rs.getString("name"));
        }
        
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        
        }
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_Assigment;
    private javax.swing.JButton Remove_delete;
    private javax.swing.JButton ShowInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_AddAssigment;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextArea jTextField_info;
    // End of variables declaration//GEN-END:variables
}
