/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.net.URI;
import java.util.Locale;
import java.util.ResourceBundle;


/**
 *
 * @author Henrik.ho
 */
public class AddCountry extends javax.swing.JFrame {
    ConnectionClass db = new ConnectionClass();
    
    private Locale l;
    
    /**
     * Creates new form AddCountry
     */
    public AddCountry() {
        initComponents();
        String CountryName = "";
        String Amount = "";
        initializeLanguage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_CountryName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JTextField();
        btn_AddCountry = new javax.swing.JButton();
        lbl_link = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Project/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("AddCountry.jLabel1.text")); // NOI18N

        txt_CountryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CountryNameActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("AddCountry.jLabel2.text")); // NOI18N

        txt_Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_AmountKeyPressed(evt);
            }
        });

        btn_AddCountry.setText(bundle.getString("AddCountry.btn_AddCountry.text")); // NOI18N
        btn_AddCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddCountryActionPerformed(evt);
            }
        });

        lbl_link.setText(bundle.getString("AddCountry.lbl_link.text")); // NOI18N
        lbl_link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_linkMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_CountryName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_AddCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_link))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_CountryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(txt_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lbl_link)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AddCountry))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CountryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CountryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CountryNameActionPerformed

    private void btn_AddCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddCountryActionPerformed
       
        try {
         db.query("insert into allowance(Country , Amount) values ('"+txt_CountryName.getText()+"' , '"+txt_Amount.getText()+"')");
           }
         catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
        /* +Status+"')"); */
     
// TODO add your handling code here:
    }//GEN-LAST:event_btn_AddCountryActionPerformed

    private void txt_AmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AmountKeyPressed
if(evt.getKeyCode() ==KeyEvent.VK_ENTER){ 
    try {
            db.query("insert into allowance(Country , Amount) values ('"+txt_CountryName.getText()+"' , '"+txt_Amount.getText()+"')");
                                                                                                                  
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Det gick inte att lägga till detta Land");
        }

}
    }//GEN-LAST:event_txt_AmountKeyPressed

    private void lbl_linkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_linkMousePressed
        // TODO add your handling code here:
        try{
            String URL = "http://www.skatteverket.se/privat/skatter/arbeteinkomst/traktamente/utlandstraktamente.4.2b543913a42158acf800016035.html";
        java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }       
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
      }

    }//GEN-LAST:event_lbl_linkMousePressed
        
    private void initializeLanguage(){
        l = LogIn.getString();
         
        ResourceBundle r = ResourceBundle.getBundle("Project/Bundle", l);
        
        btn_AddCountry.setText(r.getString("AddCountry.btn_AddCountry.text"));
         jLabel2.setText(r.getString("AddCountry.jLabel2.text"));
          jLabel1.setText(r.getString("AddCountry.jLabel1.text"));
           lbl_link.setText(r.getString("AddCountry.lbl_link.text"));            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCountry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCountry().setVisible(true);
            }
        });
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_link;
    private javax.swing.JTextField txt_Amount;
    private javax.swing.JTextField txt_CountryName;
    // End of variables declaration//GEN-END:variables
}
