
package Project;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrik
 */
public class AddTravelAdvances2 extends javax.swing.JInternalFrame {
    ConnectionClass db = new ConnectionClass();
    /**
     * Creates new form NewJInternalFrame
     */
    public AddTravelAdvances2() {
        initComponents();
        fillBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbox_assignment = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_info = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();

        cbox_assignment.setMaximumRowCount(999);
        cbox_assignment.setToolTipText("");

        jLabel1.setText("Amount:");

        jLabel2.setText("Reason for travel advance:");

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_send)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_amount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_info, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbox_assignment, javax.swing.GroupLayout.Alignment.LEADING, 0, 129, Short.MAX_VALUE))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cbox_assignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_send)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        int travelID;
        String name = cbox_assignment.getSelectedItem().toString();
        try{
           travelID =  db.getID("select assignmentid from assignment where name = '"+name+"'");
            db.query("insert into traveladvances(amount, approved, assignmentid, reason) values("+
                    txt_amount.getText()+", 0, "+travelID+", '"+txt_info.getText()+"')");
        }catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }//GEN-LAST:event_btn_sendActionPerformed

    private void fillBoxes(){
        ResultSet names = db.getColumn("select * from assignment");
        int numOfUsers;
        try{
            numOfUsers = db.getCount("assignment");
            for (int i=0; i<numOfUsers; i++)
            {
            names.next();
            cbox_assignment.addItem(names.getString("name"));
            }
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JComboBox cbox_assignment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_info;
    // End of variables declaration//GEN-END:variables
}

