/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Gaspar
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    
    
    public static String currentLoggedInID;
    private static Locale l;
    public LogIn() {
        initComponents();
        Internet();
        this.getRootPane().setDefaultButton(btn_login);
        l = new Locale("sv","SE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_loginUser = new javax.swing.JTextField();
        pass_loginPassword = new javax.swing.JPasswordField();
        label_loginUsername = new javax.swing.JLabel();
        label_loginPassword = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        label_offline = new javax.swing.JLabel();
        label_welcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnSwedish = new javax.swing.JButton();
        BtnEnglish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pass_loginPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_loginPasswordKeyPressed(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Project/Bundle"); // NOI18N
        label_loginUsername.setText(bundle.getString("LogIn.label_loginUsername.text")); // NOI18N

        label_loginPassword.setText(bundle.getString("LogIn.label_loginPassword.text")); // NOI18N

        btn_login.setText(bundle.getString("LogIn.btn_login.text")); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        label_offline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_offline.setText(bundle.getString("LogIn.label_offline.text")); // NOI18N

        label_welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_welcome.setText(bundle.getString("LogIn.label_welcome.text")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/logga2.gif"))); // NOI18N

        BtnSwedish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/se.png"))); // NOI18N
        BtnSwedish.setText(bundle.getString("LogIn.BtnSwedish.text")); // NOI18N
        BtnSwedish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSwedishActionPerformed(evt);
            }
        });

        BtnEnglish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/uk-small.jpg"))); // NOI18N
        BtnEnglish.setText(bundle.getString("LogIn.BtnEnglish.text")); // NOI18N
        BtnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnglishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(188, 188, 188)
                            .addComponent(label_welcome))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_offline, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_login)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass_loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(130, 130, 130)
                .addComponent(BtnSwedish, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BtnEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_welcome)
                    .addComponent(BtnSwedish, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(label_loginUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_loginPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pass_loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btn_login)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_offline, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Showbtn(){
    
        label_offline.setVisible(true);
    
    
    }
    
    private void Hidebtn(){
    
        label_offline.setVisible(false);
       
    }
    
    
    
    public boolean Internet() { 
    try {                                                                                                                                                                                                                                 
        final URL url = new URL("http://www.google.com");                                                                                                                                                                                 
        final URLConnection check = url.openConnection();                                                                                                                                                                                  
             check.connect();
               System.out.println("har internet");      
               Hidebtn();
               return true;
                       
    }   
    catch (MalformedURLException e) { 
        System.out.println("Har inte internet");
        Showbtn();
        throw new RuntimeException(e);                                                                                                                                                                                                    
    } catch (IOException e) {                
        System.out.println("har inte internet");
           return false;                                                                                                                                                                                                                   
    }    
      
 }  

    
    // hate
    
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String username = txt_loginUser.getText();
        String password = pass_loginPassword.getText();
        
        if(Validation.logInCheck(username, password)){
            this.dispose();
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void pass_loginPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_loginPasswordKeyPressed
        if(evt.getKeyCode() ==KeyEvent.VK_ENTER){      
            String username = txt_loginUser.getText();
                String password = pass_loginPassword.getText();

        if(Validation.logInCheck(username, password)){
            this.dispose();
        }
    
}
    }//GEN-LAST:event_pass_loginPasswordKeyPressed

    private void BtnSwedishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSwedishActionPerformed
        // TODO add your handling code here:
        l = new Locale("sv","SE");
        ResourceBundle r = ResourceBundle.getBundle("Project/Bundle", l);
        
        label_welcome.setText(r.getString("LogIn.label_welcome.text"));
         label_offline.setText(r.getString("LogIn.label_offline.text"));
          btn_login.setText(r.getString("LogIn.btn_login.text"));
           label_loginPassword.setText(r.getString("LogIn.label_loginPassword.text"));
            label_loginUsername.setText(r.getString("LogIn.label_loginUsername.text"));
    }//GEN-LAST:event_BtnSwedishActionPerformed

    private void BtnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnglishActionPerformed
        // TODO add your handling code here:
        l = new Locale("en","US");
        ResourceBundle r = ResourceBundle.getBundle("Project/Bundle", l);
        
        label_welcome.setText(r.getString("LogIn.label_welcome.text"));
         label_offline.setText(r.getString("LogIn.label_offline.text"));
          btn_login.setText(r.getString("LogIn.btn_login.text"));
           label_loginPassword.setText(r.getString("LogIn.label_loginPassword.text"));
            label_loginUsername.setText(r.getString("LogIn.label_loginUsername.text"));
        
    }//GEN-LAST:event_BtnEnglishActionPerformed
    
    
        public static Locale getString(){
            return l;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnglish;
    private javax.swing.JButton BtnSwedish;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_loginPassword;
    private javax.swing.JLabel label_loginUsername;
    private javax.swing.JLabel label_offline;
    private javax.swing.JLabel label_welcome;
    private javax.swing.JPasswordField pass_loginPassword;
    private javax.swing.JTextField txt_loginUser;
    // End of variables declaration//GEN-END:variables
}
