/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author josefin
 */
public class ManageUsers extends javax.swing.JInternalFrame {
    ConnectionClass db = new ConnectionClass();
    /**
     * Creates new form ManageUser
     */
    public ManageUsers() {
        initComponents();
        fillBoxes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_names = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldMail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        box_Status1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel_AddUserName = new javax.swing.JLabel();
        jLabel_AddUserNameEmail = new javax.swing.JLabel();
        jLabel_AddNewUserName = new javax.swing.JLabel();
        jLabel_AddPassword = new javax.swing.JLabel();
        jLabel_AddUserNameStatus = new javax.swing.JLabel();
        box_Status = new javax.swing.JComboBox();
        txt_UserName = new javax.swing.JTextField();
        txt_UserEmail = new javax.swing.JTextField();
        txt_UsernameName = new javax.swing.JTextField();
        jButton_AddUserSave = new javax.swing.JButton();
        txt_Password = new javax.swing.JPasswordField();
        jLabel_NewUser = new javax.swing.JLabel();

        setTitle("Manage users");
        setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Delete User");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Users:");

        list_names.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_names.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_namesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_names);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(394, 394, 394))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Name");

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        jLabel3.setText("Email");

        label3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        label3.setText("Status");

        jButton2.setText("Update User Information");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Update user information:");

        box_Status1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consultant", "Boss" }));
        box_Status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Status1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPassword)
                            .addComponent(box_Status1, 0, 230, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(box_Status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_AddUserName.setText("Full name:");

        jLabel_AddUserNameEmail.setText("Email:");

        jLabel_AddNewUserName.setText("Username:");

        jLabel_AddPassword.setText("Password:");

        jLabel_AddUserNameStatus.setText("Status:");

        box_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boss", "Consultant" }));
        box_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_StatusActionPerformed(evt);
            }
        });

        txt_UsernameName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameNameActionPerformed(evt);
            }
        });

        jButton_AddUserSave.setText("Save");
        jButton_AddUserSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddUserSaveActionPerformed(evt);
            }
        });

        jLabel_NewUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_NewUser.setText("Add a new user:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_AddNewUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_AddUserNameEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_AddUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_AddPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_AddUserNameStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txt_UserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txt_UsernameName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jButton_AddUserSave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Password)
                            .addComponent(box_Status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel_NewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel_NewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AddUserName)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AddUserNameEmail)
                    .addComponent(txt_UserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AddNewUserName)
                    .addComponent(txt_UsernameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AddPassword)
                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AddUserNameStatus)
                    .addComponent(box_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AddUserSave)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       deleteUser();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
updateUser();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void box_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_StatusActionPerformed
        /*Object SelectedItem = box_Status.getSelectedItem();
        String Boss = "Boss";

        // SelectedItem = SelectedItem.toString();
        if(SelectedItem.equals(Boss)){
            int Bossvalue = Integer.parseInt(Boss);
            System.out.println(Boss);
        }
        */
        // TODO add your handling code here:
    }//GEN-LAST:event_box_StatusActionPerformed

    private void txt_UsernameNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameNameActionPerformed

    private void jButton_AddUserSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddUserSaveActionPerformed

        String name = txt_UserName.getText();
        String email = txt_UserEmail.getText();
        String user = txt_UsernameName.getText();
        String pass = txt_Password.getText();
        String status = box_Status.getSelectedItem().toString();
        
        addNewUser(name, email, user, pass, status);
        fillBoxes();
    }//GEN-LAST:event_jButton_AddUserSaveActionPerformed

    private void list_namesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_namesValueChanged
        informationUser();
    }//GEN-LAST:event_list_namesValueChanged

    private void box_Status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Status1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_Status1ActionPerformed

    private void fillBoxes(){
        
        ResultSet names = db.getColumn("select * from users");
        int numOfUsers;
        try {
            numOfUsers = db.getCount("users");
            DefaultListModel DLM = new DefaultListModel();
            for (int i=0; i<numOfUsers; i++) {
                names.next();
                
                DLM.addElement(names.getString("username"));
                list_names.setModel(DLM);

            }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
}
    }
    
    public void deleteUser() {
        String selectedItem = list_names.getSelectedValue().toString();
        
        try{
               String sqlDelete = "Delete from users where username ='" + selectedItem +"'";
              db.query(sqlDelete);
               fillBoxes();

           }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(null,"Something went wrong");
           }}
    
    public void informationUser() {
        
        String selectedItem = list_names.getSelectedValue().toString();
        try {
            String sqlName = "Select name from  users where username ='" + selectedItem +"'";                //Sedan fylls information på i de tomma fälten när sql frågorna körs.

            String sqlEmail = "Select email from  users where username ='" + selectedItem +"'";  

            String sqlUserName = "Select username from  users where username ='" + selectedItem +"'";  
            String sqlPassword = "Select password from  users where username ='" + selectedItem +"'";  
            String sqlStatus = "Select status from  users where username ='" + selectedItem +"'";

            String TheName = db.getString(sqlName);
            fieldName.setText(TheName);
            
            String TheEmail = db.getString(sqlEmail);
            fieldMail.setText(TheEmail);
            
            String TheUserName = db.getString(sqlUserName);
            fieldUserName.setText(TheUserName);
            
            String ThePassword = db.getString(sqlPassword);
            fieldPassword.setText(ThePassword);
            
            if(db.getString(sqlStatus).equals("1")){
                box_Status1.setSelectedIndex(1);
            }
            else if(db.getString(sqlStatus).equals("0")){
                box_Status1.setSelectedIndex(0);
            }
                    

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void updateUser() {                //Går igenom alla fält och uppdaterar dem med en sql-fråga för varje fält, som körs vid anropning av metoden.     

        String selectedItem = list_names.getSelectedValue().toString();
        
        String name = fieldName.getText();
        String mail = fieldMail.getText();
        String userName = fieldUserName.getText();
        String password = fieldPassword.getText();
        int status = 0;
        
        if(box_Status1.getSelectedItem().toString() == "Boss"){
            status = 1;
        }

        String sqlName = "update users set name = '" + name + "' where username ='" + selectedItem +"'"; 
        String sqlMail = "update users set email = '" + mail + "' where username ='" + selectedItem +"'"; 
        String sqluserName = "update users set username = '" + userName + "' where username ='" + selectedItem +"'"; 
        String sqlPassword = "update users set password = '" + password + "' where username ='" + selectedItem +"'"; 
        String sqlStatus = "update users set status = '" + status + "' where username ='" + selectedItem +"'";         
        try {

            db.query(sqlName);
            db.query(sqlMail);
            db.query(sqluserName);
            db.query(sqlPassword);
            db.query(sqlStatus);

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Meddelande",
                    JOptionPane.ERROR_MESSAGE);

        }
    
    

        

    }
    
    public void addNewUser(String name, String email, String user, String pass, String status){             
        int uStatus = 0;        
        if (status.equals("Boss")){
            uStatus = 1;
           }        
        
        if(Validation.validateUser(name, email, user, pass)){
            try {
             db.query("insert into users(name, email, username, password, status) values ("
                     + "'" +name+ "', "
                     + " '"+email+"',"
                     + " '"+user+"',"
                     + " '"+pass+"',"
                     + " '"+uStatus+"')");
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Could not create a new user.");
            }
        }
    }
            
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox box_Status;
    private javax.swing.JComboBox box_Status1;
    private javax.swing.JTextField fieldMail;
    private javax.swing.JTextField fieldName;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_AddUserSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_AddNewUserName;
    private javax.swing.JLabel jLabel_AddPassword;
    private javax.swing.JLabel jLabel_AddUserName;
    private javax.swing.JLabel jLabel_AddUserNameEmail;
    private javax.swing.JLabel jLabel_AddUserNameStatus;
    private javax.swing.JLabel jLabel_NewUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label3;
    private javax.swing.JList list_names;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserEmail;
    private javax.swing.JTextField txt_UserName;
    private javax.swing.JTextField txt_UsernameName;
    // End of variables declaration//GEN-END:variables
}
